### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by sddoe**
Pull request for feature-branch containing the project "Design Teardown". This project is a collaborative project and is a heatmap of the Smashing Magazine page so it is made up of a navigation bar, a container for the articles and a footer section with space between each section.

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :1234: [Required Changes] :1234: 
___
Hi @sddoe and @mariosknl :wave: ,
Awesome job :clap: , project contains a readme, code looks neat and clean. No error on html markup validator :clap: . I think there are two more contents that are catching my eye too. Lets add those and declare this project as complete.
___
### :spades: [Mandatory Changes] :spades: 
___
1. It contains 3 articles, each takes one third of the width([link to page](https://www.smashingmagazine.com/))
2. ##### Footer
    It contains centered links ([link to page](https://www.smashingmagazine.com/)). But you have covered that part using a p tag.
3. Linter is not showing any status. Can you recheck about enabling stickler on your project by this [link](https://stickler-ci.com/)
image
If you have done all the steps to enable stickler properly, then for sure you have enabled it after all the commits have been pushed on the repo. As soon as you push a commit it will be functional.
___
##### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

**Comment by mariosknl** [comment]
We fixed all the issues mentioned.

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Hi!

The project is looking great, but need some improvements before merging:

- [x] Use the [article tag](https://www.w3schools.com/tags/tag_article.asp) for all the articles listed on the page:
image
- [x] Footer should contain centered links (content is not important).

Since the page is responsive and changes across different screen widths, try to base your layout on the 1440px layout so we all can agree on the same design:
image

Keep up the good work! The project is coming out great 🥇.

Status: **Request changes**.

**Comment by sddoe** [comment]
Fixed footer, article and layout issues

**Review by mosesogwo — APPROVED** [review]
**Hi @mariosknl, @sddoe, great job so far... Your project is approved!**

Please use hyperlinks in your README for a neat outlook. See how here https://stackoverflow.com/a/52436163

**Cheers:smile:**

**Status: Approved!**

**Pull request merged**
